baseURL = "https://hualet.org/"
languageCode = "zh-cn"
title = "Think in Hualet"
disqusShortname = "hualetblog"

theme = "hyde-x"

[author]
    name = "Hualet Wang"

[permalinks]
    post = "/blog/:year/:month/:day/:title/"

[params]

    hideReadingTime = true
    
    highlight = "sunburst"
    
    gravatarHash = "d07d3626f19b0a5c353eff86d03d0e8f"
	googleAnalytics = "UA-121092907-1"
    
    tagline = "Think in Hualet"
    
    # sidebar 
    github = "https://github.com/hualet"
    twitter = "https://twitter.com/Hualet"
    googleplus = "https://plus.google.com/+%E8%80%80%E5%8D%8E%E7%8E%8B"
    
    rss = true
